# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170714_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
